### ISSUE TITLE
Add test vectors

### ISSUE THREAD

**Issue by pbtrung** [lynxlynx/tfcrypt_public#2]
Encryption is hard and computer program always has bugs.
Adding some test vectors from the Skein submission would make this more reliable.

Anyway, the tool is quite good and I do appreciate your efforts on its docs.
Thanks,
Trung

**Comment by lynxlynx** [comment]
The basic self tests are here: Skein reference submission data in various flavors (data from empty to 256 bytes, zero block and decrementing byte block as in submission) plus Skein1024 operating in lesser bits output hash mode (for example, Skein1024-160).
Threefish tests consist of basic modes testing with my own static reference data input (a 2k byte block), for which, there are Skein hashes of successful encrypted data for each mode. Decryption tests are performed as well. The test runs in default mode which tfcrypt_defs.h describes.

The tests and vectors are currently not a part of tf1024 because of possible bloat issues, however they are designed to be easily included alongside with the implementation as it uses only standard headers and tf1024.h header and it's not tied to tfcrypt internals.

The program will give you a message in case if self test had failed, but it will not halt. This message must appear in all the modes tfcrypt supports in case of failure.

Documentation is still stalled, however I think I will pull more examples soon out of my head.
