### ISSUE TITLE
Does keeping the EME tweak key secret improve the encryption bit strenght in tfcrypt?

### ISSUE THREAD

**Issue by christopher-mv** [lynxlynx/tfcrypt_public#3]
I read that EME mode turns a n-bit block cipher in a mn-bit enciphering scheme (1 pass of EME can double the bit strength of encryption): https://eprint.iacr.org/2014/009.pdf

As I have been testing, the tweak key for EME in tfcrypt is inserted with -c option and uses a 128 bytes key file (the same number of bytes are used for CBC as a Initialization Vector).

Does tfcrypt provide 2048 bits encryption if I use a 128 bytes raw key file together with a 128 bytes tweak key for EME?

**Comment by lynxlynx** [comment]
Sorry, EME mode paper describes has nothing to do with tfcrypt's "eme". The name is misleading, and I will probably rename the mode soon. This "eme" is simply CTR mode with second encryption pass of result.

Apart from that I believe keeping IV/counter/nonce secret _cannot_ improve security even if tfcrypt by default derives counter from key and keeps it secret (by just not telling it to anyone). Thus, no 2048 bits security for you. But still, 1024 bits is far better from "just enough" today.
Even if that, you may achieve 2048 bits security with just any other mode since changing the single bit of IV changes result ciphertext drastically and it works with both CTR and CBC too.

If in doubts, you should use TCTR mode: it takes the real tweak value (128 bits) which is a Threefish built-in and iterates over it instead of a counter. It has these nice features of both CBC and CTR modes combined: full parallelism and resistance to bit flipping attacks, and it is suitable for disk encryption as well. While EME implemented here also has these features, it has nothing to do with official EME, and it twice slower than TCTR.
